/* orouteragent - emulated gateway model profiles
 *
 * These tables define protocol-visible hardware capabilities and component
 * versions. Field presence is part of the management contract, so update a
 * profile as one coherent unit and review the encoded negotiation payload.
 */
#include "profiles.h"

#include <ctype.h>
#include <string.h>

static const struct ora_component g_ER605_components[] = {
    { "abnormalDetect", "1.1" },
    { "abnormalDt", "1.0" },
    { "acl", "1.2" },
    { "aclDisable", "1.0" },
    { "arpInform", "0.0" },
    { "arpTable", "1.0" },
    { "attackDefense", "1.1" },
    { "bandwidthCtrl", "1.0" },
    { "client", "0.0" },
    { "clientInform", "0.0" },
    { "clientIpBinding", "1.0" },
    { "clientOpt", "0.0" },
    { "clientTrafficRequire", "0.0" },
    { "configVersion", "0.0" },
    { "connect", "1.0" },
    { "controllerInfo", "0.0" },
    { "ctTable", "1.0" },
    { "ddns", "1.1" },
    { "ddnsStats", "1.0" },
    { "devInform", "0.0" },
    { "dst", "0.0" },
    { "echoServer", "1.0" },
    { "facebookV2", "1.1" },
    { "firewallConfig", "1.0" },
    { "hwOffload", "1.0" },
    { "igmp", "1.1" },
    { "informInterval", "1.1" },
    { "ipGroup", "1.0" },
    { "ipMacBinding", "1.0" },
    { "ipPortGroup", "1.0" },
    { "ipsecFailover", "1.1" },
    { "iptv", "1.1" },
    { "iptv_hw", "1.0" },
    { "ipv6Group", "1.0" },
    { "led", "1.0" },
    { "lldp", "1.0" },
    { "logInform", "0.0" },
    { "mdns", "1.1" },
    { "mirror", "1.0" },
    { "natAlg", "1.0" },
    { "natPf", "1.0" },
    { "network", "1.0" },
    { "networkTraffic", "0.0" },
    { "oneToOneNat", "1.0" },
    { "onlineDetection", "1.1" },
    { "policyRouting", "1.1" },
    { "port", "1.0" },
    { "portInfo", "0.0" },
    { "portalAct", "0.0" },
    { "portalDuration", "1.0" },
    { "portalFreePolicy", "1.0" },
    { "portforward", "1.0" },
    { "privacyPolicy", "1.0" },
    { "qos", "1.0" },
    { "rebootSchedule", "1.0" },
    { "routingTable", "1.0" },
    { "serviceType", "1.0" },
    { "sessionLimit", "1.0" },
    { "sideParams", "1.0" },
    { "snmp", "1.0" },
    { "snmpAdvance", "1.0" },
    { "speedDuplex", "1.0" },
    { "speedTest", "1.0" },
    { "ssh", "1.0" },
    { "staticRouting", "1.0" },
    { "system", "0.0" },
    { "time", "0.0" },
    { "timeRange", "0.0" },
    { "trafficStat", "0.0" },
    { "upnp", "1.0" },
    { "urlFiltering", "1.1" },
    { "userAcnt", "0.0" },
    { "vpn", "1.3" },
    { "vpnUsers", "1.1" },
    { "wanBasicSetting", "1.0" },
    { "wanIpv4", "1.2" },
    { "wanIpv6", "1.0" },
    { "wanLoadBalance", "1.0" },
    { "wanMac", "1.0" },
};
static const struct ora_port_info g_ER605_ports[] = {
    { .port = 1, .name = "WAN", .type = 0, .mode = 0,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 2, .name = "WAN/LAN1", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 3, .name = "WAN/LAN2", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 4, .name = "WAN/LAN3", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 5, .name = "LAN", .type = 2, .mode = 1,
      .has_max_bandwidth = false, .max_bandwidth = 0, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
};
static const struct ora_spec g_ER605_spec = {
    .acl_num = 64,
    .bandwidth_ctrl_num = 64,
    .client_ip_binding_num = 1024,
    .ddns_num = 24,
    .ip_group_num = 512,
    .ipv6_group_num = 512,
    .ldap_class_rules_num = 8,
    .nat_pf_num = 32,
    .network_num = 128,
    .policy_routing_num = 64,
    .qos_class_rules_num = 32,
    .service_type_num = 128,
    .session_limit_num = 64,
    .ssl_vpn_connections_num = 500,
    .ssl_vpn_locks_num = 1000,
    .ssl_vpn_resource_groups_num = 128,
    .ssl_vpn_resources_num = 64,
    .ssl_vpn_user_groups_num = 256,
    .ssl_vpn_users_num = 512,
    .static_routing_num = 64,
    .url_filtering_num = 64,
    .vpn_ipsec_num = 20,
    .vpn_l2tp_client_num = 10,
    .vpn_openvpn_num = 10,
    .vpn_pptp_client_num = 10,
    .vpn_users_num = 240,
    .wireguard_all_peer_num = 100,
    .wireguard_num = 20,
    .wireguard_peer_num = 20,
};
static const struct ora_component g_ER706W_components[] = {
    { "abnormalDetect", "1.1" },
    { "abnormalDt", "1.0" },
    { "acl", "1.2" },
    { "aclDisable", "1.0" },
    { "arpInform", "0.0" },
    { "arpTable", "1.0" },
    { "attackDefense", "1.1" },
    { "bandwidthCtrl", "1.0" },
    { "client", "0.0" },
    { "clientInform", "0.0" },
    { "clientIpBinding", "1.0" },
    { "clientOpt", "0.0" },
    { "clientTrafficRequire", "0.0" },
    { "configVersion", "0.0" },
    { "connect", "1.0" },
    { "controllerInfo", "0.0" },
    { "ctTable", "1.0" },
    { "ddns", "1.1" },
    { "ddnsStats", "1.0" },
    { "devInform", "0.0" },
    { "dsl", "1.0" },
    { "dst", "0.0" },
    { "echoServer", "1.0" },
    { "facebookV2", "1.1" },
    { "firewallConfig", "1.0" },
    { "hwOffload", "1.0" },
    { "igmp", "1.1" },
    { "informInterval", "1.1" },
    { "ipGroup", "1.0" },
    { "ipMacBinding", "1.0" },
    { "ipPortGroup", "1.0" },
    { "ipsecFailover", "1.1" },
    { "iptv", "1.1" },
    { "iptv_hw", "1.0" },
    { "ipv6Group", "1.0" },
    { "led", "1.0" },
    { "lldp", "1.0" },
    { "logInform", "0.0" },
    { "lte", "1.0" },
    { "mdns", "1.1" },
    { "mirror", "1.0" },
    { "natAlg", "1.0" },
    { "natPf", "1.0" },
    { "network", "1.0" },
    { "networkTraffic", "0.0" },
    { "oneToOneNat", "1.0" },
    { "onlineDetection", "1.1" },
    { "policyRouting", "1.1" },
    { "port", "1.0" },
    { "portInfo", "0.0" },
    { "portalAct", "0.0" },
    { "portalDuration", "1.0" },
    { "portalFreePolicy", "1.0" },
    { "portforward", "1.0" },
    { "privacyPolicy", "1.0" },
    { "qos", "1.0" },
    { "rebootSchedule", "1.0" },
    { "routingTable", "1.0" },
    { "serviceType", "1.0" },
    { "sessionLimit", "1.0" },
    { "sideParams", "1.0" },
    { "snmp", "1.0" },
    { "snmpAdvance", "1.0" },
    { "speedDuplex", "1.0" },
    { "speedTest", "1.0" },
    { "ssh", "1.0" },
    { "staticRouting", "1.0" },
    { "system", "0.0" },
    { "time", "0.0" },
    { "timeRange", "0.0" },
    { "trafficStat", "0.0" },
    { "upnp", "1.0" },
    { "urlFiltering", "1.1" },
    { "userAcnt", "0.0" },
    { "vpn", "1.3" },
    { "vpnUsers", "1.1" },
    { "wanBasicSetting", "1.0" },
    { "wanIpv4", "1.2" },
    { "wanIpv6", "1.0" },
    { "wanLoadBalance", "1.0" },
    { "wanMac", "1.0" },
};
static const struct ora_port_info g_ER706W_ports[] = {
    { .port = 1, .name = "WAN", .type = 0, .mode = 0,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 2, .name = "WAN/LAN1", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 3, .name = "WAN/LAN2", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 4, .name = "WAN/LAN3", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 5, .name = "LAN", .type = 2, .mode = 1,
      .has_max_bandwidth = false, .max_bandwidth = 0, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
};
static const struct ora_spec g_ER706W_spec = {
    .acl_num = 128,
    .bandwidth_ctrl_num = 128,
    .client_ip_binding_num = 1024,
    .ddns_num = 24,
    .ip_group_num = 512,
    .ipv6_group_num = 512,
    .ldap_class_rules_num = 8,
    .nat_pf_num = 64,
    .network_num = 128,
    .policy_routing_num = 64,
    .qos_class_rules_num = 32,
    .service_type_num = 128,
    .session_limit_num = 64,
    .ssl_vpn_connections_num = 1000,
    .ssl_vpn_locks_num = 2000,
    .ssl_vpn_resource_groups_num = 128,
    .ssl_vpn_resources_num = 64,
    .ssl_vpn_user_groups_num = 256,
    .ssl_vpn_users_num = 512,
    .static_routing_num = 64,
    .url_filtering_num = 64,
    .vpn_ipsec_num = 50,
    .vpn_l2tp_client_num = 50,
    .vpn_openvpn_num = 50,
    .vpn_pptp_client_num = 50,
    .vpn_users_num = 500,
    .wireguard_all_peer_num = 200,
    .wireguard_num = 50,
    .wireguard_peer_num = 50,
};
static const struct ora_component g_ER7206_components[] = {
    { "abnormalDetect", "1.1" },
    { "abnormalDt", "1.0" },
    { "acl", "1.2" },
    { "aclDisable", "1.0" },
    { "arpInform", "0.0" },
    { "arpTable", "1.0" },
    { "attackDefense", "1.1" },
    { "bandwidthCtrl", "1.0" },
    { "client", "0.0" },
    { "clientInform", "0.0" },
    { "clientIpBinding", "1.0" },
    { "clientOpt", "0.0" },
    { "clientTrafficRequire", "0.0" },
    { "configVersion", "0.0" },
    { "connect", "1.0" },
    { "controllerInfo", "0.0" },
    { "ctTable", "1.0" },
    { "ddns", "1.1" },
    { "ddnsStats", "1.0" },
    { "devInform", "0.0" },
    { "dsl", "1.0" },
    { "dst", "0.0" },
    { "echoServer", "1.0" },
    { "facebookV2", "1.1" },
    { "firewallConfig", "1.0" },
    { "hwOffload", "1.0" },
    { "igmp", "1.1" },
    { "informInterval", "1.1" },
    { "ipGroup", "1.0" },
    { "ipMacBinding", "1.0" },
    { "ipPortGroup", "1.0" },
    { "ipsecFailover", "1.1" },
    { "iptv", "1.1" },
    { "iptv_hw", "1.0" },
    { "ipv6Group", "1.0" },
    { "led", "1.0" },
    { "lldp", "1.0" },
    { "logInform", "0.0" },
    { "mdns", "1.1" },
    { "mirror", "1.0" },
    { "natAlg", "1.0" },
    { "natPf", "1.0" },
    { "network", "1.0" },
    { "networkTraffic", "0.0" },
    { "oneToOneNat", "1.0" },
    { "onlineDetection", "1.1" },
    { "policyRouting", "1.1" },
    { "port", "1.0" },
    { "portInfo", "0.0" },
    { "portalAct", "0.0" },
    { "portalDuration", "1.0" },
    { "portalFreePolicy", "1.0" },
    { "portforward", "1.0" },
    { "privacyPolicy", "1.0" },
    { "qos", "1.0" },
    { "rebootSchedule", "1.0" },
    { "routingTable", "1.0" },
    { "sdwan", "1.0" },
    { "serviceType", "1.0" },
    { "sessionLimit", "1.0" },
    { "sideParams", "1.0" },
    { "snmp", "1.0" },
    { "snmpAdvance", "1.0" },
    { "speedDuplex", "1.0" },
    { "speedTest", "1.0" },
    { "ssh", "1.0" },
    { "staticRouting", "1.0" },
    { "system", "0.0" },
    { "time", "0.0" },
    { "timeRange", "0.0" },
    { "trafficStat", "0.0" },
    { "upnp", "1.0" },
    { "urlFiltering", "1.1" },
    { "userAcnt", "0.0" },
    { "virtualWan", "1.0" },
    { "vpn", "1.3" },
    { "vpnUsers", "1.1" },
    { "wanBasicSetting", "1.0" },
    { "wanIpv4", "1.2" },
    { "wanIpv6", "1.0" },
    { "wanLoadBalance", "1.0" },
    { "wanMac", "1.0" },
};
static const struct ora_port_info g_ER7206_ports[] = {
    { .port = 1, .name = "WAN1", .type = 0, .mode = 0,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 2, .name = "WAN2/LAN1", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 3, .name = "WAN3/LAN2", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 4, .name = "WAN4/LAN3", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 5, .name = "LAN4", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 6, .name = "LAN5", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 7, .name = "LAN6", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 8, .name = "LAN7", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 9, .name = "SFP", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 10000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "3:2" }, .n_speed_duplex = 2,
      .support_internet_vlan = 1, .support_iptv = 0,
      .support_mirror = 1, .support_poe = 0 },
};
static const struct ora_spec g_ER7206_spec = {
    .acl_num = 256,
    .bandwidth_ctrl_num = 128,
    .client_ip_binding_num = 1024,
    .ddns_num = 24,
    .ip_group_num = 512,
    .ipv6_group_num = 512,
    .ldap_class_rules_num = 8,
    .nat_pf_num = 64,
    .network_num = 128,
    .policy_routing_num = 64,
    .qos_class_rules_num = 32,
    .service_type_num = 128,
    .session_limit_num = 64,
    .ssl_vpn_connections_num = 2000,
    .ssl_vpn_locks_num = 4000,
    .ssl_vpn_resource_groups_num = 128,
    .ssl_vpn_resources_num = 64,
    .ssl_vpn_user_groups_num = 256,
    .ssl_vpn_users_num = 1024,
    .static_routing_num = 64,
    .url_filtering_num = 64,
    .vpn_ipsec_num = 100,
    .vpn_l2tp_client_num = 100,
    .vpn_openvpn_num = 100,
    .vpn_pptp_client_num = 100,
    .vpn_users_num = 1000,
    .wireguard_all_peer_num = 500,
    .wireguard_num = 100,
    .wireguard_peer_num = 100,
};

/* components_v2 from the controller ER707-M2 device template (119 entries) */
static const struct ora_component g_ER707M2_components[] = {
    { "time", "1.0" },
    { "system", "1.0" },
    { "dst", "1.0" },
    { "userAcnt", "1.0" },
    { "configVersion", "1.0" },
    { "controllerInfo", "1.1" },
    { "uiConfigSync", "1.1" },
    { "wanBasicSetting", "1.0" },
    { "onlineDetection", "1.1" },
    { "wanIpv4", "1.8" },
    { "wanIpv4Usb", "1.1" },
    { "connect", "1.0" },
    { "wanMac", "1.0" },
    { "virtualWan", "1.1" },
    { "wanLoadBalance", "1.1" },
    { "speedTest", "1.2" },
    { "speedTestSchedule", "1.0" },
    { "portalFreePolicy", "1.0" },
    { "network", "1.5" },
    { "wanIpv6", "1.1" },
    { "acl", "1.5" },
    { "macFilter", "1.0" },
    { "domainGroup", "1.1" },
    { "attackDefense", "1.2" },
    { "ipMacBinding", "1.2" },
    { "urlFiltering", "1.2" },
    { "firewallConfig", "1.0" },
    { "natPf", "1.2" },
    { "portforward", "1.0" },
    { "oneToOneNat", "1.0" },
    { "disableNat", "1.1" },
    { "natAlg", "1.1" },
    { "bandwidthCtrl", "1.0" },
    { "sessionLimit", "1.1" },
    { "iptv", "1.1" },
    { "iptv_hw", "1.0" },
    { "mld", "1.0" },
    { "common", "1.0" },
    { "led", "1.0" },
    { "snmp", "1.0" },
    { "hwOffload", "1.0" },
    { "lldp", "1.0" },
    { "echoServer", "1.0" },
    { "port", "1.0" },
    { "standaloneMgmt", "1.0" },
    { "ddns", "1.2" },
    { "snmpAdvance", "1.0" },
    { "ssh", "1.0" },
    { "upnp", "1.0" },
    { "mdns", "1.1" },
    { "rebootSchedule", "1.0" },
    { "dnsProxy", "1.1" },
    { "dpiProtocols", "1.3" },
    { "dpiTraffic", "0.0" },
    { "dnsCache", "1.0" },
    { "lanDns", "1.1" },
    { "staticRouting", "1.0" },
    { "policyRouting", "1.4" },
    { "routingTable", "1.0" },
    { "clientIpBinding", "1.0" },
    { "wireguard", "1.1" },
    { "sslVpnV2", "1.3" },
    { "sslVpnStats", "1.0" },
    { "sdwan", "1.1" },
    { "vpn", "1.7" },
    { "vpnUsers", "1.1" },
    { "ipsecFailover", "1.1" },
    { "radiusProfile", "1.1" },
    { "ipGroup", "1.0" },
    { "ipv6Group", "1.0" },
    { "ipPortGroup", "1.0" },
    { "timeRange", "1.0" },
    { "serviceType", "1.0" },
    { "macGroup", "1.0" },
    { "ipv6PortGroup", "1.0" },
    { "countryGroup", "1.0" },
    { "ldap", "1.1" },
    { "qos", "1.0" },
    { "ping", "1.1" },
    { "traceroute", "1.1" },
    { "dnslookup", "1.0" },
    { "arptable", "1.0" },
    { "abnormalDetect", "1.1" },
    { "packageCapture", "1.1" },
    { "transferChannel", "1.0" },
    { "fileTransfer", "1.0" },
    { "terminalSetting", "1.0" },
    { "deviceDebugInfo", "1.0" },
    { "dhcpClient", "1.1" },
    { "backupConfig", "1.1" },
    { "controllerSetting", "1.0" },
    { "informInterval", "1.1" },
    { "natTraversal", "1.0" },
    { "deviceMonitor", "1.1" },
    { "monitorInform", "1.0" },
    { "devInform", "1.0" },
    { "arpInform", "1.0" },
    { "clientInform", "1.0" },
    { "portInfo", "1.0" },
    { "virtualWanInfo", "0.0" },
    { "trafficStat", "1.0" },
    { "networkTraffic", "1.0" },
    { "logInform", "1.1" },
    { "alertInform", "1.0" },
    { "logNotification", "1.0" },
    { "portalAct", "1.1" },
    { "client", "0.0" },
    { "clientOpt", "1.0" },
    { "clientTrafficRequire", "0.0" },
    { "privacyPolicy", "1.0" },
    { "speedDuplex", "1.0" },
    { "mirror", "1.0" },
    { "ddnsStats", "1.1" },
    { "ips", "1.0" },
    { "ipsWhiteList", "1.0" },
    { "ipsBlackList", "1.0" },
    { "signatureList", "1.0" },
    { "blockCountry", "1.0" },
    { "interval", "1.1" },
};

/* ER707-M2: 7 ports - 2x 2.5G RJ45 (1 WAN, 1 WAN/LAN), 4x Gigabit RJ45
 * WAN/LAN, 1x Gigabit SFP WAN/LAN. Port names/types follow the ER7206
 * convention; the two 2.5G ports report 2500 Mbps. */
static const struct ora_port_info g_ER707M2_ports[] = {
    /* ER707-M2 protocol identity and capability values */
    { .port = 1, .name = "2.5G WAN1", .type = 3, .mode = 0,
      .has_max_bandwidth = true, .max_bandwidth = 2500, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2", "4:2" }, .n_speed_duplex = 7,
      .support_internet_vlan = 1, .support_iptv = 0,
      .support_mirror = 0, .support_poe = 0 },
    { .port = 2, .name = "2.5G WAN/LAN2", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 2500, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2", "4:2" }, .n_speed_duplex = 7,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 3, .name = "WAN/LAN3", .type = 1, .mode = 0,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 4, .name = "WAN/LAN4", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 5, .name = "WAN/LAN5", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 6, .name = "WAN/LAN6", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 7, .name = "SFP WAN/LAN7", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
};
static const struct ora_spec g_ER707M2_spec = {
    /* values from the controller's ER707-M2 template (devCap.specification) */
    .acl_num = 64,
    .bandwidth_ctrl_num = 64,
    .client_ip_binding_num = 2048,
    .ddns_num = 24,
    .ip_group_num = 512,
    .ipv6_group_num = 512,
    .ldap_class_rules_num = 8,
    .nat_pf_num = 128,
    .network_num = 128,
    .policy_routing_num = 64,
    .qos_class_rules_num = 32,
    .service_type_num = 128,
    .session_limit_num = 128,
    .ssl_vpn_connections_num = 60,
    .ssl_vpn_locks_num = 1000,
    .ssl_vpn_resource_groups_num = 128,
    .ssl_vpn_resources_num = 64,
    .ssl_vpn_user_groups_num = 256,
    .ssl_vpn_users_num = 512,
    .static_routing_num = 128,
    .url_filtering_num = 128,
    .vpn_ipsec_num = 100,
    .vpn_l2tp_client_num = 12,
    .vpn_openvpn_num = 7,
    .vpn_pptp_client_num = 12,
    .vpn_users_num = 270,
    .wireguard_all_peer_num = 100,
    .wireguard_num = 20,
    .wireguard_peer_num = 20,
};
static const struct ora_component g_ER8411_components[] = {
    { "abnormalDetect", "1.1" },
    { "abnormalDt", "1.0" },
    { "acl", "1.2" },
    { "aclDisable", "1.0" },
    { "arpInform", "0.0" },
    { "arpTable", "1.0" },
    { "attackDefense", "1.1" },
    { "bandwidthCtrl", "1.0" },
    { "client", "0.0" },
    { "clientInform", "0.0" },
    { "clientIpBinding", "1.0" },
    { "clientOpt", "0.0" },
    { "clientTrafficRequire", "0.0" },
    { "configVersion", "0.0" },
    { "connect", "1.0" },
    { "controllerInfo", "0.0" },
    { "ctTable", "1.0" },
    { "ddns", "1.1" },
    { "ddnsStats", "1.0" },
    { "devInform", "0.0" },
    { "dsl", "1.0" },
    { "dst", "0.0" },
    { "echoServer", "1.0" },
    { "facebookV2", "1.1" },
    { "firewallConfig", "1.0" },
    { "hwOffload", "1.0" },
    { "igmp", "1.1" },
    { "informInterval", "1.1" },
    { "ipGroup", "1.0" },
    { "ipMacBinding", "1.0" },
    { "ipPortGroup", "1.0" },
    { "ipsecFailover", "1.1" },
    { "iptv", "1.1" },
    { "iptv_hw", "1.0" },
    { "ipv6Group", "1.0" },
    { "led", "1.0" },
    { "lldp", "1.0" },
    { "logInform", "0.0" },
    { "mdns", "1.1" },
    { "mirror", "1.0" },
    { "natAlg", "1.0" },
    { "natPf", "1.0" },
    { "network", "1.0" },
    { "networkTraffic", "0.0" },
    { "oneToOneNat", "1.0" },
    { "onlineDetection", "1.1" },
    { "policyRouting", "1.1" },
    { "port", "1.0" },
    { "portInfo", "0.0" },
    { "portalAct", "0.0" },
    { "portalDuration", "1.0" },
    { "portalFreePolicy", "1.0" },
    { "portforward", "1.0" },
    { "privacyPolicy", "1.0" },
    { "qos", "1.0" },
    { "rebootSchedule", "1.0" },
    { "routingTable", "1.0" },
    { "sdwan", "1.0" },
    { "serviceType", "1.0" },
    { "sessionLimit", "1.0" },
    { "sideParams", "1.0" },
    { "snmp", "1.0" },
    { "snmpAdvance", "1.0" },
    { "speedDuplex", "1.0" },
    { "speedTest", "1.0" },
    { "ssh", "1.0" },
    { "staticRouting", "1.0" },
    { "system", "0.0" },
    { "time", "0.0" },
    { "timeRange", "0.0" },
    { "trafficStat", "0.0" },
    { "upnp", "1.0" },
    { "urlFiltering", "1.1" },
    { "userAcnt", "0.0" },
    { "virtualWan", "1.0" },
    { "vpn", "1.3" },
    { "vpnUsers", "1.1" },
    { "wanBasicSetting", "1.0" },
    { "wanIpv4", "1.2" },
    { "wanIpv6", "1.0" },
    { "wanLoadBalance", "1.0" },
    { "wanMac", "1.0" },
};
static const struct ora_port_info g_ER8411_ports[] = {
    { .port = 1, .name = "WAN1/SFP1", .type = 0, .mode = 0,
      .has_max_bandwidth = true, .max_bandwidth = 10000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 2, .name = "WAN2/LAN1", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 3, .name = "WAN3/LAN2", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 4, .name = "LAN3", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 5, .name = "LAN4", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 6, .name = "LAN5", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 7, .name = "LAN6", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 8, .name = "LAN7", .type = 2, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 1000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "1:1", "1:2", "2:1", "2:2", "3:2" }, .n_speed_duplex = 6,
      .support_internet_vlan = 1, .support_iptv = 1,
      .support_mirror = 1, .support_poe = 0 },
    { .port = 9, .name = "SFP2", .type = 1, .mode = 1,
      .has_max_bandwidth = true, .max_bandwidth = 10000, .default_speed_duplex = "0:0",
      .speed_duplex_list = { "0:0", "3:2" }, .n_speed_duplex = 2,
      .support_internet_vlan = 1, .support_iptv = 0,
      .support_mirror = 1, .support_poe = 0 },
};
static const struct ora_spec g_ER8411_spec = {
    .acl_num = 512,
    .bandwidth_ctrl_num = 256,
    .client_ip_binding_num = 2048,
    .ddns_num = 24,
    .ip_group_num = 1024,
    .ipv6_group_num = 1024,
    .ldap_class_rules_num = 16,
    .nat_pf_num = 128,
    .network_num = 256,
    .policy_routing_num = 128,
    .qos_class_rules_num = 64,
    .service_type_num = 256,
    .session_limit_num = 128,
    .ssl_vpn_connections_num = 5000,
    .ssl_vpn_locks_num = 10000,
    .ssl_vpn_resource_groups_num = 256,
    .ssl_vpn_resources_num = 128,
    .ssl_vpn_user_groups_num = 512,
    .ssl_vpn_users_num = 2048,
    .static_routing_num = 128,
    .url_filtering_num = 128,
    .vpn_ipsec_num = 200,
    .vpn_l2tp_client_num = 200,
    .vpn_openvpn_num = 200,
    .vpn_pptp_client_num = 200,
    .vpn_users_num = 2000,
    .wireguard_all_peer_num = 500,
    .wireguard_num = 200,
    .wireguard_peer_num = 200,
};

/* Index into g_profiles serving as the default (ER707-M2). */
enum { ORA_PROFILE_DEFAULT_ER707M2 = 3 };

static const struct ora_model_profile g_profiles[] = {
    {
        .name = "er605",
        .model = "ER605", .model_ver = "1.0", .hw_ver = "1.0",
        .fw_ver = "1.3.2 Build 20240528 Rel.73864",
        .hw_id = "22CA512B4F6AA46358DDE15569E3E93E", .encrypted_hw_id = "22CA512B4F6AA46358DDE15569E3E93E",
        .oem_id = "9D109CE88890A6A02AC0F21CEA998EEC", .encrypted_oem_id = "9D109CE88890A6A02AC0F21CEA998EEC",
        .lan_mac_template = "00-FF-00-12-7A-D4",
        .wireless = 0,
        .components = g_ER605_components, .n_components = 79,
        .ports = g_ER605_ports, .n_ports = 5,
        .spec = &g_ER605_spec,
        .port_num = 5, .extra_port = 0, .usb_lte_wan = 0,
        .ipsec_num = 20,
        .max_ssl_vpn_user_concurrent_num = 100,
        .max_vpn_user_concurrent_num = 100,
        .default_igmp_wan = 1,
        .mandatory_ports = NULL, .n_mandatory_ports = 0,
        .extra_port_infos = NULL, .n_extra_port_infos = 0,
        .support_acl_disable = 1,
        .support_all_wan = true,
        .has_wlb = false, .support_wan_load_balance = false,
        .has_discrete_wan = true, .support_discrete_wan = 0,
        .has_lte = false, .support_lte = false,
        .has_sdwan = false, .support_sdwan = false,
        .support_ipsec_failover = 1,
        .support_routing_vpn_client = 1,
        .support_vpn_usb = 0,
        .support_vpn_verify = 1,
        .supports_ipv6 = true,
        .support_poe = false,
    },
    {
        .name = "er706w",
        .model = "ER706W", .model_ver = "1.0", .hw_ver = "1.0",
        .fw_ver = "1.2.0 Build 20240315 Rel.54321",
        .hw_id = "A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6", .encrypted_hw_id = "A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6",
        .oem_id = "F1E2D3C4B5A69788796A5B4C3D2E1F00", .encrypted_oem_id = "F1E2D3C4B5A69788796A5B4C3D2E1F00",
        .lan_mac_template = "00-FF-00-12-7A-D4",
        .wireless = 1,
        .components = g_ER706W_components, .n_components = 81,
        .ports = g_ER706W_ports, .n_ports = 5,
        .spec = &g_ER706W_spec,
        .port_num = 5, .extra_port = 0, .usb_lte_wan = 1,
        .ipsec_num = 50,
        .max_ssl_vpn_user_concurrent_num = 200,
        .max_vpn_user_concurrent_num = 200,
        .default_igmp_wan = 1,
        .mandatory_ports = NULL, .n_mandatory_ports = 0,
        .extra_port_infos = NULL, .n_extra_port_infos = 0,
        .support_acl_disable = 1,
        .support_all_wan = true,
        .has_wlb = true, .support_wan_load_balance = 1,
        .has_discrete_wan = true, .support_discrete_wan = 1,
        .has_lte = true, .support_lte = 1,
        .has_sdwan = false, .support_sdwan = false,
        .support_ipsec_failover = 1,
        .support_routing_vpn_client = 1,
        .support_vpn_usb = 1,
        .support_vpn_verify = 1,
        .supports_ipv6 = true,
        .support_poe = false,
    },
    {
        .name = "er7206",
        .model = "ER7206", .model_ver = "1.0", .hw_ver = "1.0",
        .fw_ver = "1.0.0 Build 20240101 Rel.11111",
        .hw_id = "B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7", .encrypted_hw_id = "B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7",
        .oem_id = "E2D3C4B5A69788796A5B4C3D2E1F0011", .encrypted_oem_id = "E2D3C4B5A69788796A5B4C3D2E1F0011",
        .lan_mac_template = "00-FF-00-12-7A-D4",
        /* wired router: the ER7206 profile has no on-board radio */
        .wireless = 0,
        .components = g_ER7206_components, .n_components = 82,
        .ports = g_ER7206_ports, .n_ports = 9,
        .spec = &g_ER7206_spec,
        .port_num = 9, .extra_port = 0, .usb_lte_wan = 0,
        .ipsec_num = 100,
        .max_ssl_vpn_user_concurrent_num = 500,
        .max_vpn_user_concurrent_num = 500,
        .default_igmp_wan = 1,
        .mandatory_ports = NULL, .n_mandatory_ports = 0,
        .extra_port_infos = NULL, .n_extra_port_infos = 0,
        .support_acl_disable = 1,
        .support_all_wan = true,
        .has_wlb = true, .support_wan_load_balance = 1,
        .has_discrete_wan = true, .support_discrete_wan = 1,
        .has_lte = false, .support_lte = false,
        .has_sdwan = true, .support_sdwan = 1,
        .support_ipsec_failover = 1,
        .support_routing_vpn_client = 1,
        .support_vpn_usb = 0,
        .support_vpn_verify = 1,
        .supports_ipv6 = true,
        .support_poe = false,
    },
    {
        .name = "er707m2",
        .model = "ER707-M2", .model_ver = "1.0", .hw_ver = "1.0",
        .fw_ver = "1.4.0 Build 20251208 Rel.72306",
        .hw_id = "0F92EFE7EAAA0097BEAE28F4ADCA45F8", .encrypted_hw_id = "0F92EFE7EAAA0097BEAE28F4ADCA45F8",
        .oem_id = "A0F6555C524BF352168A7AB7FCBBFD0C", .encrypted_oem_id = "A0F6555C524BF352168A7AB7FCBBFD0C",
        .lan_mac_template = "00-FF-00-12-7A-D4",
        /* wired router: no on-board radio */
        .wireless = 0,
        .components = g_ER707M2_components, .n_components = 119,
        .ports = g_ER707M2_ports, .n_ports = 7,
        .spec = &g_ER707M2_spec,
        .port_num = 7, .extra_port = 0, .usb_lte_wan = 1,
        .ipsec_num = 100,
        .max_ssl_vpn_user_concurrent_num = 60,
        .max_vpn_user_concurrent_num = 60,
        .default_igmp_wan = 3,
        .mandatory_ports = NULL, .n_mandatory_ports = 0,
        .extra_port_infos = NULL, .n_extra_port_infos = 0,
        .support_acl_disable = 1,
        .support_all_wan = true,
        .has_wlb = true, .support_wan_load_balance = 1,
        .has_discrete_wan = true, .support_discrete_wan = 1,
        .has_lte = false, .support_lte = false,
        .has_sdwan = true, .support_sdwan = 1,
        .support_ipsec_failover = 1,
        .support_routing_vpn_client = 1,
        .support_vpn_usb = 0,
        .support_vpn_verify = 1,
        .supports_ipv6 = true,
        .support_poe = false,
    },
    {
        .name = "er8411",
        .model = "ER8411", .model_ver = "1.0", .hw_ver = "1.0",
        .fw_ver = "1.0.0 Build 20240101 Rel.22222",
        .hw_id = "C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8", .encrypted_hw_id = "C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8",
        .oem_id = "D3C4B5A69788796A5B4C3D2E1F001122", .encrypted_oem_id = "D3C4B5A69788796A5B4C3D2E1F001122",
        .lan_mac_template = "00-FF-00-12-7A-D4",
        /* wired router: SFP+ ports, no on-board radio */
        .wireless = 0,
        .components = g_ER8411_components, .n_components = 82,
        .ports = g_ER8411_ports, .n_ports = 9,
        .spec = &g_ER8411_spec,
        .port_num = 9, .extra_port = 0, .usb_lte_wan = 0,
        .ipsec_num = 200,
        .max_ssl_vpn_user_concurrent_num = 1000,
        .max_vpn_user_concurrent_num = 1000,
        .default_igmp_wan = 1,
        .mandatory_ports = NULL, .n_mandatory_ports = 0,
        .extra_port_infos = NULL, .n_extra_port_infos = 0,
        .support_acl_disable = 1,
        .support_all_wan = true,
        .has_wlb = true, .support_wan_load_balance = 1,
        .has_discrete_wan = true, .support_discrete_wan = 1,
        .has_lte = false, .support_lte = false,
        .has_sdwan = true, .support_sdwan = 1,
        .support_ipsec_failover = 1,
        .support_routing_vpn_client = 1,
        .support_vpn_usb = 0,
        .support_vpn_verify = 1,
        .supports_ipv6 = true,
        .support_poe = false,
    },
};


const struct ora_model_profile *ora_profiles_all(size_t *n)
{
    if (n)
        *n = sizeof(g_profiles) / sizeof(g_profiles[0]);
    return g_profiles;
}

const struct ora_model_profile *ora_profile_lookup(const char *model)
{
    size_t i;

    /* model name with separators ("ER707-M2", "er707 m2") normalizes to
     * the profile key (alphanumeric, lower case). */
    char key[64];
    size_t j = 0;

    if (!model || !*model)
        return &g_profiles[ORA_PROFILE_DEFAULT_ER707M2];
    for (i = 0; model[i] && j + 1 < sizeof(key); i++) {
        if (isalnum((unsigned char)model[i]))
            key[j++] = (char)tolower((unsigned char)model[i]);
    }
    key[j] = '\0';
    for (i = 0; i < sizeof(g_profiles) / sizeof(g_profiles[0]); i++) {
        if (strcmp(g_profiles[i].name, key) == 0)
            return &g_profiles[i];
    }
    /* unknown -> default ER707-M2 (warn at caller) */
    return &g_profiles[ORA_PROFILE_DEFAULT_ER707M2];
}

